# Generated by Django 4.2 on 2023-04-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.CharField(blank=True, max_length=11, verbose_name='Дата создания'),
        ),
    ]
