# Generated by Django 4.2 on 2023-04-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0002_alter_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('message', models.CharField(max_length=256, verbose_name='Отзыв')),
                ('date', models.CharField(blank=True, max_length=11, verbose_name='Дата создания')),
            ],
        ),
    ]
